spring.application.name=library

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=123456

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=none  # IMPORTANTE: Usamos 'none' porque la BD ya está creada
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC

# Opcional: Mostrar parámetros de consultas SQL
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE